In [1]:
import pandas as pd
df = pd.read_csv("data_given\email_phishing_data.csv")
df

,num_words,num_unique_words,num_stopwords,num_links,num_unique_domains,num_email_addresses,num_spelling_errors,num_urgent_keywords,label
0,140,94,52,0,0,0,0,0,0
1,5,5,1,0,0,0,0,0,0
2,34,32,15,0,0,0,0,0,0
3,6,6,2,0,0,0,0,0,0
4,9,9,2,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...
524841,782,327,301,2,2,2,52,1,0
524842,36,30,11,0,0,0,4,0,1
524843,61,46,11,0,0,0,3,0,0
524844,213,136,89,0,0,0,18,0,0
524845,26,24,3,0,0,0,2,0,0

In [2]:
df.columns

Index(['num_words', 'num_unique_words', 'num_stopwords', 'num_links',
       'num_unique_domains', 'num_email_addresses', 'num_spelling_errors',
       'num_urgent_keywords', 'label'],
      dtype='object')

In [3]:
df['label'].value_counts()

label
0    517897
1      6949
Name: count, dtype: int64

In [5]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
num_words,524846.0,276.228000,3335.456750,0.0,47.0,120.0,269.0,2339682.0
num_unique_words,524846.0,123.012167,201.626478,0.0,38.0,79.0,145.0,51251.0
num_stopwords,524846.0,80.045465,1023.330380,0.0,12.0,34.0,79.0,720411.0
num_links,524846.0,0.895588,5.603001,0.0,0.0,0.0,0.0,824.0
num_unique_domains,524846.0,0.347767,1.774209,0.0,0.0,0.0,0.0,524.0
num_email_addresses,524846.0,2.114897,13.592682,0.0,0.0,0.0,1.0,1150.0
num_spelling_errors,524846.0,24.694731,311.312358,0.0,2.0,8.0,22.0,190104.0
num_urgent_keywords,524846.0,0.245301,0.559320,0.0,0.0,0.0,0.0,7.0
label,524846.0,0.013240,0.114301,0.0,0.0,0.0,0.0,1.0